# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('age', models.IntegerField(null=False)),
                ('sex', models.IntegerField()),
                ('spayed', models.BooleanField()),
                ('size', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=45)),
                ('fostered', models.BooleanField()),
                ('acquired_date', models.DateField(auto_now_add=True)),
                ('breed_id_fk', models.IntegerField()),
                ('image', models.CharField(max_length=250)),
            ],
        ),
    ]
