# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20191128_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(default='unknown'),
        ),
    ]
