# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_pet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=b''),
        ),
    ]
