# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20191128_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
