# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_pet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_id',
            field=models.CharField(default='No ID', max_length=8),
        ),
    ]
