# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_pet_pet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.TextField(default='default.jpeg'),
        ),
    ]
