# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20191129_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='acquired_date',
            field=models.DateField(),
        ),
    ]
