# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-30 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20191130_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='acquired_date',
            field=models.DateField(),
        ),
    ]
