# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-30 06:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20191130_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='size',
        ),
        migrations.AlterField(
            model_name='pet',
            name='acquired_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 30, 6, 1, 17, 240126, tzinfo=utc)),
        ),
    ]
